/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"


#include "IfxPort.h"
#include "IfxPort_PinMap.h"

#define PCn_2_IDX 19
#define PCn_1_IDX 11
#define PCn_0_IDX 3
//#define P10_IOCR0 (*(volatile Ifx_P_IOCR0*)0xF003B000u)
#define P2_IDX 2
#define P1_IDX 1
#define P0_IDX 0
#define EXIS0_IDX 4
#define EXIS1_IDX 20
#define FEN0_IDX 8
#define FEN1_IDX 24
#define REN0_IDX 9
#define REN1_IDX 25
#define EIEN0_IDX 11
#define EIEN1_IDX 27
#define INP0_IDX 12
#define INP1_IDX 28
#define IGP0_IDX 14
#define IGP1_IDX 30
#define SRE_IDX 10
#define TOS_IDX 11

IfxCpu_syncEvent g_cpuSyncEvent = 0;
volatile uint32 cnt=0;

void initLED(void);
void initGPIO(void);

unsigned int prev=2;
unsigned int cur=1;
unsigned int flag=0;
volatile uint8 ledblinkstate=1; //안눌리면 LED BLINK모드가 켜져있는
volatile uint8 ledblinkstate2=1;
IFX_INTERRUPT(ISR0,0,0x10);
IFX_INTERRUPT(ISR1,0,0x20);

void ISR0(void){//sw 2에 대한
    //P10_OUT.U=0x1<<P2_IDX;//blue
    P10_OUT.U=0x1<<P1_IDX;//red on

}

void ISR1(void){ //sw 1에 대한
    P10_OUT.U=0x1<<P2_IDX;//blue on

}

void core0_main(void)
{

    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);

    initGPIO();
    //P10_OUT.U=0x1<<P1_IDX;

    while(1)
    {
        IfxPort_setPinHigh(IfxPort_P10_2.port,IfxPort_P10_2.pinIndex);
    }
}

void initLED(void){
    P10_IOCR0.U&=~(0x1F<<PCn_2_IDX); //19
    P10_IOCR0.U|=0x10<<PCn_2_IDX;
}
void initGPIO(void){

    P10_IOCR0.U&=~(0x1F<<PCn_2_IDX); //19
    P10_IOCR0.U|=0x10<<PCn_2_IDX;

    P10_IOCR0.U&=~(0x1F<<PCn_1_IDX); // Red
    P10_IOCR0.U|=0x10<<PCn_1_IDX;

    P02_IOCR0.U&=~(0x1f <<PCn_1_IDX);//switch2
    P02_IOCR0.U|=0x02<<PCn_1_IDX;

    //sw1 D2
    P02_IOCR0.U&=~(0x1f<<PCn_0_IDX);
    P02_IOCR0.U|=0x02<<PCn_0_IDX;



    //sw2 Interrupt
    //ERU
    SCU_EICR1.U&=~(0x7<<EXIS0_IDX);
    SCU_EICR1.U|=0x1<<EXIS0_IDX;

    //falling
    SCU_EICR1.U|=1<<FEN0_IDX;
    //rising
    //SCU_EICR1.U|=1<<REN0_IDX;
    SCU_EICR1.U|=1<<EIEN0_IDX;

    SCU_EICR1.U&=~(0x7<<INP0_IDX);

    //OGU
    SCU_IGCR0.U&=~(0x3<<IGP0_IDX);
    SCU_IGCR0.U|=0x1<<IGP0_IDX; //14

    SRC_SCU_SCU_ERU0.U&=~0xFF;
    SRC_SCU_SCU_ERU0.U|=0x10; //SPRN
    SRC_SCU_SCU_ERU0.U|=1<<SRE_IDX;//1
    SRC_SCU_SCU_ERU0.U&=~(0x3<<TOS_IDX); //TOS 0=>CPU0

    //sw1 interrupt ERS3 EICR1 i=1
    SCU_EICR1.U&=~(0x7<<EXIS1_IDX);
    SCU_EICR1.U|=0x2<<EXIS1_IDX;

    SCU_EICR1.U|=1<<FEN1_IDX;
    SCU_EICR1.U|=1<<EIEN1_IDX;
    SCU_EICR1.U|=(0x1<<INP1_IDX); //ogu1

    //output설정 out1-> IGP1--> j=0
    SCU_IGCR0.U&=~(0x1<<IGP1_IDX);
    SCU_IGCR0.U|=0x1<<IGP1_IDX;

    SRC_SCU_SCU_ERU1.U&=~0xFF;
    SRC_SCU_SCU_ERU1.U|=0x20; //Sw1 iv 주소
    SRC_SCU_SCU_ERU1.U|=1<<SRE_IDX;//1
    SRC_SCU_SCU_ERU1.U&=~(0x3<<TOS_IDX); //TOS 0=>CPU0
}
