/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"

#include "IfxPort.h"
#include "IfxPort_PinMap.h"

#include "Driver_Stm.h"
#include "Driver_Adc.h"

//GPIO related
#define PCn_2_IDX 19
#define P2_IDX 2
#define PCn_1_IDX 11
#define P1_IDX 1

// ERU related
#define EXIS0_IDX 4
#define FEN0_IDX 8
#define EIEN0_IDX 11
#define INP0_IDX 12
#define IGP0_IDX 14

// SRC related
#define SRE_IDX 10
#define TOS_IDX 11

typedef struct
{
    uint32 u32nuCnt1ms;
    uint32 u32nuCnt10ms;
    uint32 u32nuCnt100ms;
    uint32 u32nuCnt1000ms;

}TestCnt;

// Task scheduling related
void AppScheduling(void);
void AppTask1ms(void);
void AppTask10ms(void);
void AppTask100ms(void);
void AppTask1000ms(void);


/***********************************************************************/
/*Variable*/
/***********************************************************************/
TestCnt stTestCnt;

IfxCpu_syncEvent g_cpuSyncEvent = 0;
uint32 adcResult=0;
uint32 adc46Result=0;
unsigned char _LED_0F[10]={0xC0,0xF9,0xA4,0xB0,0x99, 0x92,0x82,0xF8,0x80,0x90};
void initGPIO(void);
void initERU(void);

void send(unsigned char X);
void send_port(unsigned char X, unsigned char port);

int core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);

    initGPIO();
    Driver_Stm_Init();
    Driver_Adc_Init();
    uint32 n8,n4,n2,n1;
    uint32 tmp;
    while(1)
    {


        AppScheduling();

        //tmp=adcResult;
        tmp=adc46Result;
        n1=tmp%10;
        tmp/=10;
        n2=tmp%10;
        tmp/=10;
        n4=tmp%10;
        tmp/=10;
        n8=tmp%10;
        send_port(_LED_0F[n8],0x8);
        send_port(_LED_0F[n4],0x4);
        send_port(_LED_0F[n2],0x2);
        send_port(_LED_0F[n1],0x1);

    }
    return (1);
}

void initGPIO(void){
    P02_IOCR0.U &= ~(0x1F << PCn_1_IDX);
    P02_IOCR0.U |= 0x02 << PCn_1_IDX;

    P10_IOCR0.U &= ~(0x1F << PCn_2_IDX);
    P10_IOCR0.U |= 0x10 << PCn_2_IDX;

    P10_IOCR0.U &= ~(0x1F << PCn_1_IDX);
    P10_IOCR0.U |= 0x10 << PCn_1_IDX;


    //spi
    IfxPort_setPinMode(IfxPort_P00_0.port, IfxPort_P00_0.pinIndex, IfxPort_Mode_outputPushPullGeneral);
    IfxPort_setPinMode(IfxPort_P02_5.port, IfxPort_P02_5.pinIndex, IfxPort_Mode_outputPushPullGeneral);
    IfxPort_setPinMode(IfxPort_P02_6.port, IfxPort_P02_6.pinIndex, IfxPort_Mode_outputPushPullGeneral);

    //adc
    IfxPort_setPinMode(IfxPort_P02_7.port, IfxPort_P02_7.pinIndex, IfxPort_Mode_outputPushPullGeneral);
    IfxPort_setPinMode(IfxPort_P10_5.port, IfxPort_P10_5.pinIndex, IfxPort_Mode_outputPushPullGeneral);
    IfxPort_setPinMode(IfxPort_P10_3.port, IfxPort_P10_3.pinIndex, IfxPort_Mode_outputPushPullGeneral);

    //조도센서 A1

}
void send(unsigned char X)
{

  for (int i = 8; i >= 1; i--)
  {
    if (X & 0x80)
    {
        //P23_OUT.U=0x1<<2; //dio
        ///P00_OUT.U=0x1<<0; //dio
        IfxPort_setPinHigh(IfxPort_P00_0.port, IfxPort_P00_0.pinIndex);
    }
    else
    {
        //P23_OUT.U=0x0<<2; //dio
        //P00_OUT.U=0x0<<0; //dio
        IfxPort_setPinLow(IfxPort_P00_0.port, IfxPort_P00_0.pinIndex);
        //IfxPort_setPinHigh(port, pinIndex);
    }
    X <<= 1;
    IfxPort_setPinLow(IfxPort_P02_6.port, IfxPort_P02_6.pinIndex);
    IfxPort_setPinHigh(IfxPort_P02_6.port, IfxPort_P02_6.pinIndex);
    //P02_OUT.U=0x0<<6;
    //P02_OUT.U=0x1<<6;
  }
}
void send_port(unsigned char X, unsigned char port)
{
  send(X);
  send(port);
  IfxPort_setPinLow(IfxPort_P02_5.port, IfxPort_P02_5.pinIndex);
  IfxPort_setPinHigh(IfxPort_P02_5.port, IfxPort_P02_5.pinIndex);
  //P02_OUT.U=0x0<<5;
 // P02_OUT.U=0x1<<5;

}
void AppTask1ms(void)
{
    stTestCnt.u32nuCnt1ms++;
}

void AppTask10ms(void)
{
    stTestCnt.u32nuCnt10ms++;
    adc46Result=Driver_Adc4_DataObtain();
    Driver_Adc4_ConvStart();

    adcResult=Driver_Adc0_DataObtain();
    Driver_Adc0_ConvStart();
}

void AppTask100ms(void)
{
    stTestCnt.u32nuCnt100ms++;
    /*ADC Test*/




}

void AppTask1000ms(void)
{


    stTestCnt.u32nuCnt1000ms++;
    /*ADC Test*/
    //adcResult=Driver_Adc0_DataObtain();



    if(adcResult>=0&&adcResult<1300){
        IfxPort_setPinHigh(IfxPort_P02_7.port,IfxPort_P02_7.pinIndex );
        IfxPort_setPinLow(IfxPort_P10_5.port,IfxPort_P10_5.pinIndex );
        IfxPort_setPinLow(IfxPort_P10_3.port,IfxPort_P10_3.pinIndex );
    }
    else if(adcResult>=1300&&adcResult<2600){
        IfxPort_setPinLow(IfxPort_P02_7.port,IfxPort_P02_7.pinIndex );
        IfxPort_setPinHigh(IfxPort_P10_5.port,IfxPort_P10_5.pinIndex );
        IfxPort_setPinLow(IfxPort_P10_3.port,IfxPort_P10_3.pinIndex );
    }
    else if(adcResult>=2600&&adcResult<=4095){
        IfxPort_setPinLow(IfxPort_P02_7.port,IfxPort_P02_7.pinIndex );
        IfxPort_setPinLow(IfxPort_P10_5.port,IfxPort_P10_5.pinIndex );
        IfxPort_setPinHigh(IfxPort_P10_3.port,IfxPort_P10_3.pinIndex );
    }
    else{
        ;
    }

    if(adc46Result>3000){

        P10_OUT.U=0x1<<P2_IDX; //blue on
    }else{
        P10_OUT.U=0x1<<P1_IDX; //red on
    }
   // Driver_Adc0_ConvStart();


}

void AppScheduling(void)
{
    if(stSchedulingInfo.u8nuScheduling1msFlag == 1u)
    {
        stSchedulingInfo.u8nuScheduling1msFlag = 0u;
        AppTask1ms();

        if(stSchedulingInfo.u8nuScheduling10msFlag == 1u)
        {
            stSchedulingInfo.u8nuScheduling10msFlag = 0u;
            AppTask10ms();
        }

        if(stSchedulingInfo.u8nuScheduling100msFlag == 1u)
        {
            stSchedulingInfo.u8nuScheduling100msFlag = 0u;
            AppTask100ms();
        }
        if(stSchedulingInfo.u8nuScheduling1000msFlag == 1u)
        {
            stSchedulingInfo.u8nuScheduling1000msFlag = 0u;
            AppTask1000ms();
        }
    }
}
