/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"

#include "IfxPort.h"
#include "IfxPort_PinMap.h"

#include "Driver_Stm.h"

//GPIO related
#define PCn_2_IDX 19
#define P2_IDX 2
#define PCn_1_IDX 11
#define PCn_0_IDX 3
#define P1_IDX 1

//SPI port define
#define SCLK IfxPort_P00_0
#define RCLK IfxPort_P00_1
#define DIO  IfxPort_P00_2

// ERU related
#define EXIS0_IDX 4
#define FEN0_IDX 8
#define EIEN0_IDX 11
#define INP0_IDX 12
#define IGP0_IDX 14

// SRC related
#define SRE_IDX 10
#define TOS_IDX 11


uint32 u32nuCnt10ms;
// Task scheduling related
void AppScheduling(void);
void AppTask10ms(void);
void AppTask100ms(void);
void AppTask1000ms(void);

void send(uint8 X);
void send_port(uint8 X, uint8 port);


/***********************************************************************/
/*Variable*/
/***********************************************************************/

uint8 _LED_0F[10] = {0xC0,0xf9,0xa4,0xb0,0x99,0x92,0x82,0xf8,0x80,0x90};

IfxCpu_syncEvent g_cpuSyncEvent = 0;

void initGPIO(void);

int core0_main(void)
{

    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);

    initGPIO();
    Driver_Stm_Init();

    while(1)
    {
        AppScheduling();
        send_port(_LED_0F[u32nuCnt10ms % 10],0x1);
        send_port(_LED_0F[(u32nuCnt10ms/10) % 10],0x2);
        send_port(_LED_0F[(u32nuCnt10ms/100) % 10]&0x7f,0x4);
        send_port(_LED_0F[(u32nuCnt10ms/1000)],0x8);

    }
    return (1);
}

void initGPIO(void){ //GPIO 설정 초기화

    //P10_1(RED) , P10_2(BLUE) output 설정
    P10_IOCR0.U=0x00808000 ; //19 25번째

   //P00_0(sclk) , P00_1(rclk), P00_2(dio)  spi 설정
    P00_IOCR0.U=0x00808080 ;
}

void send(uint8 X){
    uint8 mask=0x80;
    for (int i = 8; i >= 1; i--)
    {
      P00_OUT.B.P2=(X&mask )? 1: 0; //DIO
      X <<= 1;
      //p00_0 sclk LOW -> HIGH
      P00_OUT.B.P0=0;
      P00_OUT.B.P0=1;

    }
}
void send_port(uint8 X, uint8 port){
    send(X);
    send(port);
    //p00_1 RCLK LOW-> HIGH
    P00_OUT.B.P1=0;
    P00_OUT.B.P1=1;
}


IFX_INLINE void AppTask10ms(void)
{
   u32nuCnt10ms++;
}

void AppTask100ms(void)
{

    P10_OUT.B.P1 ^=1; //1과 xor , RED TOGGLE

}

void AppTask1000ms(void)
{

    P10_OUT.B.P2 ^=1; //1과 xor , BLUE TOGGLE


}

void AppScheduling(void)
{

        if(stSchedulingInfo.u8nuScheduling10msFlag)
        {
            stSchedulingInfo.u8nuScheduling10msFlag = 0u;
            AppTask10ms();
        }

        if(stSchedulingInfo.u8nuScheduling100msFlag)
        {
            stSchedulingInfo.u8nuScheduling100msFlag = 0u;
            AppTask100ms();
        }
        if(stSchedulingInfo.u8nuScheduling1000msFlag)
        {
            stSchedulingInfo.u8nuScheduling1000msFlag = 0u;
            AppTask1000ms();
        }
   // }
}
