/**********************************************************************************************************************
 * \file Driver_Bluetooth.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "IfxAsclin_Asc.h"
#include "IfxPort.h"
#include "InterruptPriority.h"
#include "Driver_Bluetooth.h"
#include <string.h>
#include <stdio.h>
#include <stdarg.h>
/*********************************************************************************************************************/
/*Define*/
/***********************************************************************/
#define ASC2_TX_BUFFER_SIZE          256
#define ASC2_RX_BUFFER_SIZE          256
#define ASC2_BAUDRATE                115200  // bluetooths's base baud rate
#define USB_UART_MAX_PRINT_SIZE (255)


/***********************************************************************/
/*Variable*/
/***********************************************************************/
static IfxAsclin_Asc s_asclin2;
static uint8 s_asclin2_tx_buf[ASC2_TX_BUFFER_SIZE + sizeof(Ifx_Fifo) + 8];
static uint8 s_asclin2_rx_buf[ASC2_RX_BUFFER_SIZE + sizeof(Ifx_Fifo) + 8];


JoystickValueSet s_joystick_values;


/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
static  void send_data(pchar format);


/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/


void init_bluetooth(void) {
    IfxAsclin_Asc_Config asc_conf;

    IfxAsclin_Asc_initModuleConfig(&asc_conf, &MODULE_ASCLIN2);

    asc_conf.baudrate.baudrate = ASC2_BAUDRATE;
    asc_conf.baudrate.oversampling = IfxAsclin_OversamplingFactor_16;

    asc_conf.bitTiming.medianFilter = IfxAsclin_SamplesPerBit_three;
    asc_conf.bitTiming.samplePointPosition = IfxAsclin_SamplePointPosition_8;

    asc_conf.interrupt.txPriority = ISR_PRIORITY_ASCLIN2_TX;
    asc_conf.interrupt.rxPriority = ISR_PRIORITY_ASCLIN2_RX;
    asc_conf.interrupt.erPriority = ISR_PRIORITY_ASCLIN2_ER;
    asc_conf.interrupt.typeOfService = IfxSrc_Tos_cpu1;

    const IfxAsclin_Asc_Pins pins = {
        .cts = NULL_PTR,
        .ctsMode = IfxPort_InputMode_pullUp,
        .rx = &IfxAsclin2_RXE_P33_8_IN,
        .rxMode = IfxPort_InputMode_pullUp,
        .rts = NULL_PTR,
        .rtsMode = IfxPort_OutputMode_pushPull,
        .tx = &IfxAsclin2_TX_P33_9_OUT,
        .txMode = IfxPort_OutputMode_pushPull,
        .pinDriver = IfxPort_PadDriver_cmosAutomotiveSpeed1
    };
    asc_conf.pins = &pins;

    asc_conf.txBuffer = s_asclin2_tx_buf;
    asc_conf.txBufferSize = ASC2_TX_BUFFER_SIZE;
    asc_conf.rxBuffer = s_asclin2_rx_buf;
    asc_conf.rxBufferSize = ASC2_RX_BUFFER_SIZE;

    IfxAsclin_Asc_initModule(&s_asclin2, &asc_conf);
}


void send_bluetooth_joystick_data(uint32 x_mv, uint32 y_mv, uint32 x_rt, uint32 y_rt) {
    char message[USB_UART_MAX_PRINT_SIZE + 1];

    snprintf(message, sizeof(message), "%lu %lu %lu %lu", x_mv, y_mv, x_rt, y_rt);

    send_data(message);
}


void receive_bluetooth_joystick_data(void) {
    char buffer[USB_UART_MAX_PRINT_SIZE + 1];
    Ifx_SizeT count = 0;
    char ch;

    // Read characters into the buffer until we reach the end of the message or the buffer is full
    do {
        ch = IfxAsclin_Asc_blockingRead(&s_asclin2);
        if (ch != '\r' && ch != '\n' && count < USB_UART_MAX_PRINT_SIZE) {
            buffer[count++] = ch;
        }
    } while (ch != '\r' && ch != '\n' && count < USB_UART_MAX_PRINT_SIZE);

    buffer[count] = '\0'; // Null-terminate the string

    // Parse the received string into the JoystickValue structure
    JoystickValueSet joystick;
    if (sscanf(buffer, "%lu %lu %lu %lu", &joystick.move.x, &joystick.move.y, &joystick.rotate.x, &joystick.rotate.y) == 4) {
        s_joystick_values = joystick; // Update the global joystick value
    }
}

JoystickValueSet get_bluetooth_joystick_data(void) {
    return s_joystick_values;
}



void init_bluetooth_master(void) {
    send_data("AT"); // checking of connecting module
    send_data("AT+ROLE=1"); // setting mode to Slave
    send_data("AT+CMODE=0"); // pairing with specific module
    send_data("AT+BIND=98d3:11:fc3f58"); // binding with slave's module of address
    send_data("AT+LINK=98d3:11:fc3f58"); // linking with slave's module of address

    /*if you want to set Master, USE following codes.

      init_bluetooth_master();               <- in cpu0_Main.c

      send_data("a");                        <- Wherever you want(But, needed to include header)

      you can use the value of 'receivedChar'
    */
}

void init_bluetooth_slave(void) {
    send_data("AT"); // checking of connecting module
    send_data("AT+ROLE=0"); // setting mode to Slave

    /*if you want to set Slave, USE following codes.
         *
      init_bluetooth_slave();               <- in cpu0_Main.c

      char receivedChar = receive_data();   <- Wherever you want(But, needed to include header)

      you can use the value of 'receivedChar'
    */
}

static void send_data(pchar format) {
    char      message[USB_UART_MAX_PRINT_SIZE + 1];
    Ifx_SizeT count;
    va_list   args;
    va_start(args, format);
    vsprintf((char *)message, format, args);
    va_end(args);
    count = (Ifx_SizeT)strlen(message);
    IFX_ASSERT(IFX_VERBOSE_LEVEL_ERROR, count < STDIF_DPIPE_MAX_PRINT_SIZE);

    char *ch_ptr = message;
    char ch = *ch_ptr;
    while(ch != 0) {
        if(ch == '\n') {
            IfxAsclin_Asc_blockingWrite(&s_asclin2, '\r');
            IfxAsclin_Asc_blockingWrite(&s_asclin2, '\n');
        } else {
            IfxAsclin_Asc_blockingWrite(&s_asclin2, ch);
        }
        ch_ptr++;
        ch = *ch_ptr;
    }
}



IFX_INTERRUPT(asclin2_tx_ISR_bluetooth, 1, ISR_PRIORITY_ASCLIN2_TX);
void asclin2_tx_ISR_bluetooth(void) {
    IfxAsclin_Asc_isrTransmit(&s_asclin2);
}

IFX_INTERRUPT(asclin2_rx_ISR_bluetooth, 1, ISR_PRIORITY_ASCLIN2_RX);
void asclin2_rx_ISR_bluetooth(void) {
    IfxAsclin_Asc_isrReceive(&s_asclin2);
}

IFX_INTERRUPT(asclin2_err_ISR_bluetooth, 1, ISR_PRIORITY_ASCLIN2_ER);
void asclin2_err_ISR_bluetooth(void) {
    ;
}
